apiVersion: 1

datasources:
  - name: InfluxDB MainLab
    uid: influxdb-main
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: lics
      defaultBucket: mainLab
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}
    editable: true
